version: '3.6'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms3000m -Xmx3000m
      discovery.type: single-node
      xpack.security.enabled: false
      bootstrap.memory_lock: true
      server.maxPayload: 930070704
      savedObjects.maxImportPayloadBytes: 930070704
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'",
        ]
      interval: 10s
      timeout: 30s
      retries: 15
            
  logstash:
#    user: root
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    container_name: logstash
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/sincedb:/usr/share/logstash/data/plugins/inputs/file:rw
      - ./logstash/confs:/etc/logstash/conf.d:rw
      - ./logstash/ingest:/tmp/ingest:rw
      - ./logstash/dlq:/etc/logstash/dlq:rw
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9602:9602
    environment:
      LS_JAVA_OPTS: -Xms3000m -Xmx3000m
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: unless-stopped

  filebeat:
    user: root
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - ./filebeat:/usr/share/filebeat/filebeat_data
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: ["--strict.perms=false"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - elasticsearch
      - kibana
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "50"
  create-indices:
    image: alpine:latest
    container_name: create-indices
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./:/tmp/scripts
    command: /bin/sh -c "/usr/bin/dos2unix /tmp/scripts/createindices.sh && /bin/sh /tmp/scripts/createindices.sh"

networks:
  default:
    name: elk
